### ISSUE TITLE
Empty volume when mapped 

### ISSUE THREAD

**Issue by lukasz-kaniowski** [tutumcloud/tutum-docker-wordpress-nosql#16]
I'm using docker-compose to create wordpres container and map wp-content to host location in order of backup. directory is empty though, is there something that I'm doing wrong?

```
wordpress1:
  image: tutum/wordpress-stackable:latest
  links:
   - db
  ports:
   - "8081:80"
  volumes:
   - /backup/wp1:/app/wp-content
```
